#!/usr/bin/php
<?php
require "/usr/share/tsend/bot.php";
require "/usr/share/tsend/colors.php";
require "/usr/share/tsend/indent.php";
if(isset($argv[1]) and $argv[1] == "-h"){
	echo "by @sahagk\nUsage: ".$argv[0]." -u\tUpdate Configuration\n".$argv[0]." -i id\tCustom id to send.";
	exit;
}
if(!is_file($_SERVER['HOME']."/.tsend/tsend.conf") or (isset($argv[1]) and $argv[1] == "-u")){
	system("mkdir -p ".$_SERVER['HOME']."/.tsend");
	$colors = new Colors();
	$config = [];
	echo $colors->getColoredString("[+] Configuration","green")."\n";
	echo "Bot Token : ";
	$config["token"] = trim(fgets(STDIN));
	echo "Chat ID: ";
	$config["chat_id"] = trim(fgets(STDIN));
	$string = json_encode($config);
	file_put_contents($_SERVER['HOME']."/.tsend/tsend.conf",indent($string));
	exit;
}
$config = json_decode(file_get_contents($_SERVER['HOME']."/.tsend/tsend.conf"),true);
$str = "";
while (false !== ($line = fgets(STDIN))) {
    $str .= $line;
    echo $line;
}
$bot = new Bot($config['token']);
$token = $config['token'];
$id = $config['chat_id'];
if(isset($argv[2]) and $argv[1] == "-i") $id = $argv[2];
if(strlen($str) > 4096){
	$file = tmpfile();
	$path = stream_get_meta_data($file)['uri'];
	file_put_contents($path.".txt",$str);
	$bot->sendDocument($id,"$path.txt","STDOUT is too big");
	unlink($path);
	unlink($path.".txt");
}
else $bot->sendMessage($id,$str);
?>
